package kitty.cat.compat

import com.mojang.blaze3d.platform.InputConstants

/** Keeps the numeric key codes in existing Kittycat configs stable across the SDL migration. */
object LegacyKeyCodes {
    private val scanCodes = mapOf(
        48 to InputConstants.KEY_0,
        49 to InputConstants.KEY_1,
        50 to InputConstants.KEY_2,
        51 to InputConstants.KEY_3,
        52 to InputConstants.KEY_4,
        53 to InputConstants.KEY_5,
        54 to InputConstants.KEY_6,
        55 to InputConstants.KEY_7,
        56 to InputConstants.KEY_8,
        57 to InputConstants.KEY_9,
        65 to InputConstants.KEY_A,
        66 to InputConstants.KEY_B,
        67 to InputConstants.KEY_C,
        68 to InputConstants.KEY_D,
        69 to InputConstants.KEY_E,
        70 to InputConstants.KEY_F,
        71 to InputConstants.KEY_G,
        72 to InputConstants.KEY_H,
        73 to InputConstants.KEY_I,
        74 to InputConstants.KEY_J,
        75 to InputConstants.KEY_K,
        76 to InputConstants.KEY_L,
        77 to InputConstants.KEY_M,
        78 to InputConstants.KEY_N,
        79 to InputConstants.KEY_O,
        80 to InputConstants.KEY_P,
        81 to InputConstants.KEY_Q,
        82 to InputConstants.KEY_R,
        83 to InputConstants.KEY_S,
        84 to InputConstants.KEY_T,
        85 to InputConstants.KEY_U,
        86 to InputConstants.KEY_V,
        87 to InputConstants.KEY_W,
        88 to InputConstants.KEY_X,
        89 to InputConstants.KEY_Y,
        90 to InputConstants.KEY_Z,
        290 to InputConstants.KEY_F1,
        291 to InputConstants.KEY_F2,
        292 to InputConstants.KEY_F3,
        293 to InputConstants.KEY_F4,
        294 to InputConstants.KEY_F5,
        295 to InputConstants.KEY_F6,
        296 to InputConstants.KEY_F7,
        297 to InputConstants.KEY_F8,
        298 to InputConstants.KEY_F9,
        299 to InputConstants.KEY_F10,
        300 to InputConstants.KEY_F11,
        301 to InputConstants.KEY_F12,
        302 to InputConstants.KEY_F13,
        303 to InputConstants.KEY_F14,
        304 to InputConstants.KEY_F15,
        305 to InputConstants.KEY_F16,
        306 to InputConstants.KEY_F17,
        307 to InputConstants.KEY_F18,
        308 to InputConstants.KEY_F19,
        309 to InputConstants.KEY_F20,
        310 to InputConstants.KEY_F21,
        311 to InputConstants.KEY_F22,
        312 to InputConstants.KEY_F23,
        313 to InputConstants.KEY_F24,
        282 to InputConstants.KEY_NUMLOCK,
        320 to InputConstants.KEY_NUMPAD0,
        321 to InputConstants.KEY_NUMPAD1,
        322 to InputConstants.KEY_NUMPAD2,
        323 to InputConstants.KEY_NUMPAD3,
        324 to InputConstants.KEY_NUMPAD4,
        325 to InputConstants.KEY_NUMPAD5,
        326 to InputConstants.KEY_NUMPAD6,
        327 to InputConstants.KEY_NUMPAD7,
        328 to InputConstants.KEY_NUMPAD8,
        329 to InputConstants.KEY_NUMPAD9,
        330 to InputConstants.KEY_NUMPADCOMMA,
        335 to InputConstants.KEY_NUMPADENTER,
        336 to InputConstants.KEY_NUMPADEQUALS,
        264 to InputConstants.KEY_DOWN,
        263 to InputConstants.KEY_LEFT,
        262 to InputConstants.KEY_RIGHT,
        265 to InputConstants.KEY_UP,
        334 to InputConstants.KEY_ADD,
        39 to InputConstants.KEY_APOSTROPHE,
        92 to InputConstants.KEY_BACKSLASH,
        44 to InputConstants.KEY_COMMA,
        61 to InputConstants.KEY_EQUALS,
        96 to InputConstants.KEY_GRAVE,
        91 to InputConstants.KEY_LBRACKET,
        45 to InputConstants.KEY_MINUS,
        332 to InputConstants.KEY_MULTIPLY,
        46 to InputConstants.KEY_PERIOD,
        93 to InputConstants.KEY_RBRACKET,
        59 to InputConstants.KEY_SEMICOLON,
        47 to InputConstants.KEY_SLASH,
        32 to InputConstants.KEY_SPACE,
        258 to InputConstants.KEY_TAB,
        342 to InputConstants.KEY_LALT,
        341 to InputConstants.KEY_LCONTROL,
        340 to InputConstants.KEY_LSHIFT,
        346 to InputConstants.KEY_RALT,
        345 to InputConstants.KEY_RCONTROL,
        344 to InputConstants.KEY_RSHIFT,
        257 to InputConstants.KEY_RETURN,
        256 to InputConstants.KEY_ESCAPE,
        259 to InputConstants.KEY_BACKSPACE,
        261 to InputConstants.KEY_DELETE,
        269 to InputConstants.KEY_END,
        268 to InputConstants.KEY_HOME,
        260 to InputConstants.KEY_INSERT,
        267 to InputConstants.KEY_PAGEDOWN,
        266 to InputConstants.KEY_PAGEUP,
        280 to InputConstants.KEY_CAPSLOCK,
        284 to InputConstants.KEY_PAUSE,
        281 to InputConstants.KEY_SCROLLLOCK,
        283 to InputConstants.KEY_PRINTSCREEN
    )
    private val legacyCodes = scanCodes.entries.associate { (key, scanCode) -> scanCode to key }

    fun toScanCode(key: Int): Int = if (key < -1) -key - 2 else scanCodes[key] ?: 0

    fun fromScanCode(scanCode: Int): Int = if (scanCode == 0) -1 else legacyCodes[scanCode] ?: -scanCode - 2

    fun isDown(key: Int): Boolean {
        val scanCode = toScanCode(key)
        return scanCode != 0 && InputConstants.isKeyDown(scanCode)
    }
}